name: prophet
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alembic=1.10.2
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.0
  - cmaes=0.9.1
  - colorama=0.4.6
  - colorlog=6.7.0
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=37.0.1
  - cycler=0.11.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - giflib=5.2.1
  - greenlet=2.0.2
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - ipykernel=6.21.2
  - ipython=8.11.0
  - jedi=0.18.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.0.3
  - jupyter_core=5.2.0
  - kiwisolver=1.4.4
  - lcms2=2.14
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=15.0.7
  - libdeflate=1.17
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - mako=1.2.4
  - markupsafe=2.1.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.1
  - numpy=1.24.2
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - optuna=3.1.0
  - packaging=23.0
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - platformdirs=3.0.0
  - plotly=5.13.1
  - plotly_express=0.4.1
  - pooch=1.4.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pyyaml=6.0
  - pyzmq=25.0.0
  - readline=8.2
  - requests=2.27.1
  - scikit-learn=1.2.2
  - scipy=1.10.0
  - seaborn=0.11.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlalchemy=2.0.7
  - sqlite=3.40.1
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - tenacity=8.2.2
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - async-timeout==4.0.2
    - attrs==22.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - charset-normalizer==3.0.1
    - clikit==0.6.2
    - cmdstanpy==1.1.0
    - convertdate==2.4.0
    - crashtest==0.3.1
    - cython==0.29.33
    - defusedxml==0.7.1
    - ephem==4.1.4
    - fastjsonschema==2.16.3
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - hijri-converter==2.2.4
    - holidays==0.20
    - httpstan==4.9.1
    - idna==3.4
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - jinja2==3.1.2
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - korean-lunar-calendar==0.3.1
    - lunarcalendar==0.0.9
    - marshmallow==3.19.0
    - mistune==2.0.5
    - multidict==6.0.4
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.7.3
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - pastel==0.2.1
    - pillow==9.4.0
    - prometheus-client==0.16.0
    - prophet==1.1.2
    - pylev==1.4.0
    - pymeeus==0.5.12
    - pyrsistent==0.19.3
    - pysimdjson==5.0.2
    - pystan==3.6.0
    - python-json-logger==2.0.7
    - pytz==2022.7.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - send2trash==1.8.0
    - setuptools-git==1.2
    - sniffio==1.3.0
    - soupsieve==2.4
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tqdm==4.64.1
    - uri-template==1.2.0
    - webargs==8.2.0
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - yarl==1.8.2

